name: "Setup Godot"

description: "Downloads the specified Godot version and the Export Templates from the godotengine/godot-builds repo on GitHub."

inputs:
  version:
    description: "The version of Godot to setup"
    type: string
    required: true
  csharp:
    description: "Downloads the mono version of godot."
    type: boolean
    default: true
    required: true
  name:
    description: "The name to use for the godot executable. Defaults to 'godot'"
    default: "godot"
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Godot
      shell: bash
      run: |
        INSTALL_DIR=${HOME}/.godot-install-dir/${{ inputs.version }}
        mkdir -p $INSTALL_DIR

        echo "Creating $INSTALL_DIR"

        if [ "${{ inputs.csharp }}" = "true" ]; then
          GODOT_DOWNLOAD_URL=https://github.com/godotengine/godot-builds/releases/download/${{ inputs.version }}/Godot_v${{ inputs.version }}_mono_linux_x86_64.zip
        else
          GODOT_DOWNLOAD_URL=https://github.com/godotengine/godot-builds/releases/download/${{ inputs.version }}/Godot_v${{ inputs.version }}_linux.x86_64.zip
        fi

        echo "Downloading: $GODOT_DOWNLOAD_URL"

        cd $INSTALL_DIR
        wget -O godot.zip -q $GODOT_DOWNLOAD_URL
        unzip godot.zip
        rm -rf godot.zip

        if [ "${{ inputs.csharp }}" = "true" ]; then
          mv Godot_v${{ inputs.version }}_mono_linux_x86_64/* .
          mv Godot_v${{ inputs.version }}_mono_linux.x86_64 ${{ inputs.name }}
          rm -rf Godot_v${{ inputs.version }}_mono_linux_x86_64
        else
          mv Godot_v${{ inputs.version }}_linux.x86_64 ${{ inputs.name }}
        fi

        ls -la $INSTALL_DIR
        echo $INSTALL_DIR >> $GITHUB_PATH

    - name: Download Export Templates
      shell: bash
      run: |
        cd $RUNNER_TEMP

        if [ "${{ inputs.csharp }}" = "true" ]; then
          wget -O templates.tpz -q https://github.com/godotengine/godot-builds/releases/download/${{ inputs.version }}/Godot_v${{ inputs.version }}_mono_export_templates.tpz
          EXPORT_TEMPLATES_DIR=${HOME}/.local/share/godot/export_templates/${INPUTS_VERSION/-/.}.mono
        else
          wget -O templates.tpz -q https://github.com/godotengine/godot-builds/releases/download/${{ inputs.version }}/Godot_v${{ inputs.version }}_export_templates.tpz
          EXPORT_TEMPLATES_DIR=${HOME}/.local/share/godot/export_templates/${INPUTS_VERSION/-/.}
        fi

        unzip templates.tpz
        rm -rf templates.tpz

        mkdir -p $EXPORT_TEMPLATES_DIR
        mv ./templates/* $EXPORT_TEMPLATES_DIR
        ls -la $EXPORT_TEMPLATES_DIR
      env:
        INPUTS_VERSION: ${{ inputs.version }}
