name: "Setup Godot"

description: "Downloads the specified Godot version and the Export Templates from the godotengine/godot-builds repo on GitHub."

inputs:
  version:
    description: "The version of Godot to setup"
    type: string
    required: true
  csharp:
    description: "Downloads the mono version of godot."
    type: boolean
    default: false
    required: true
  name:
    description: "The name to use for the godot executable. Defaults to 'godot'"
    default: "godot"
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Godot
      shell: bash
      run: |
        cd $RUNNER_TEMP 
        wget -O godot.zip -q $GODOT_DOWNLOAD_URI
        unzip godot.zip 
        mkdir -p $INSTALL_DIR  
        mv Godot_v${{ inputs.version }}_linux.x86_64 $INSTALL_DIR/${{ inputs.name }} 
        echo "$INSTALL_DIR" >> $GITHUB_PATH
      env:
        INSTALL_DIR: ${HOME}/.godot-install-dir/${{ inputs.version }}
        GODOT_DOWNLOAD_URI: "https://github.com/godotengine/godot-builds/releases/download/${{ inputs.version }}/Godot_v${{ inputs.version }}_linux.x86_64.zip"

    - name: Download Export Templates
      shell: bash
      run: |
        cd $RUNNER_TEMP 
        wget -O templates.tpz -q $TEMPLATE_DOWNLOAD_URI
        unzip templates.tpz
        EXPORT_TEMPLATES_DIR=~/.local/share/godot/export_templates/${INPUTS_VERSION/-/.}
        mkdir -p $EXPORT_TEMPLATES_DIR
        mv ./templates/* $EXPORT_TEMPLATES_DIR
      env:
        INPUTS_VERSION: ${{ inputs.version }}
        TEMPLATE_DOWNLOAD_URI: "https://github.com/godotengine/godot-builds/releases/download/${{ inputs.version }}/Godot_v${{ inputs.version }}_export_templates.tpz"
