name: "Setup Godot"

description: "Downloads the specified Godot version and the Export Templates from the godotengine/godot-builds repo on GitHub."

inputs:
  version:
    description: "The version of Godot to setup"
    type: string
    required: true
  csharp:
    description: "Downloads the mono version of godot."
    type: boolean
    default: false
    required: true
  name:
    description: "The name to use for the godot executable. Defaults to 'godot'"
    default: "godot"
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Godot
      shell: bash
      run: |
        INSTALL_DIR=${HOME}/.godot-install-dir/${{ inputs.version }}
        mkdir -p $INSTALL_DIR
        cd $INSTALL_DIR

        GODOT_NAME=Godot_v${{ inputs.version }}_linux.x86_64

        wget -O godot.zip -q https://github.com/godotengine/godot-builds/releases/download/${{ inputs.version }}/${GODOT_NAME}.zip
        unzip godot.zip
        rm -f godot.zip

        mv $GODOT_NAME ${{ inputs.name }}
        rm godot.zip
        ls -la $INSTALL_DIR
        echo $INSTALL_DIR >> $GITHUB_PATH

    - name: Download Export Templates
      shell: bash
      run: |
        cd $RUNNER_TEMP
        wget -O templates.tpz -q https://github.com/godotengine/godot-builds/releases/download/${{ inputs.version }}/Godot_v${{ inputs.version }}_export_templates.tpz
        unzip templates.tpz
        EXPORT_TEMPLATES_DIR=~/.local/share/godot/export_templates/${INPUTS_VERSION/-/.}
        mkdir -p $EXPORT_TEMPLATES_DIR
        mv ./templates/* $EXPORT_TEMPLATES_DIR
      env:
        INPUTS_VERSION: ${{ inputs.version }}
