name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: ["4.3-stable", "4.4.1-stable", "4.5-dev1"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Godot
        uses: ./
        with:
          version: ${{ matrix.version }}

      - name: Confirm Godot Setup
        run: godot --version
